import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "../components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-screen h-screen flex flex-col">
          <div className="flex flex-row-reverse h-full">
            <div className="w-3/10 h-full">
              <Sidebar />
            </div>
            <div className="w-7/10 w-full flex justify-center items-center">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
